language: node_js
branches:
  only:
    - master
    - devel
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6
  - 7
  - 8
  - 9
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - npm run test:prod && npm run build
after_script: greenkeeper-lockfile-upload
after_success:
  - npm run report-coverage
  - npm run semantic-release
