version: 2
jobs:
  test-node-6:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn test
  test-node-8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn test
  test-node-9:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn test


workflows:
  version: 2
  build:
    jobs:
      - test-node-6
      - test-node-8
      - test-node-9
