version: 2
jobs:
  greenkeeper-lockfile:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: echo "test"
  test-node-6:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn test
  test-node-8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn test
  test-node-9:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn test


workflows:
  version: 2
  build:
    jobs:
      - greenkeeper-lockfile:
          filters:
            branches:
              only:
                - /greenkeeper\/.*/
      - test-node-6:
          requires:
            - greenkeeper-lockfile
      - test-node-8:
          requires:
             - greenkeeper-lockfile
      - test-node-9:
          requires:
             - greenkeeper-lockfile
